### ISSUE TITLE
Ingestion2 documentation missing IP reference

### ISSUE THREAD

**Issue by mjsuhonos** [dpla/automation#136]
The post-install initialization task described in README says:
```
$ ansible-playbook -i development -u <your username> playbooks/init_index_and_repos.yml --extra-vars "level=development create_test_account=true"
```
However, this depends on an DNS entry for:
```
192.168.50.6    webapp1
```
Which is not referenced / provided in the instructions for Ingestion2, causing the playbook to fail with:
```
GATHERING FACTS *************************************************************** 
fatal: [webapp1] => SSH Error: ssh: connect to host 192.168.50.6 port 22: Operation timed out
    while connecting to 192.168.50.6:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [Delete any existing river] ********************************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting
```

**Comment by anarchivist** [comment]
I see two issues here:

1) The command won't succeed at all unless you specify the `ingestion` inventory, e.g. `ansible-playbook -i ingestion ...` instead. 
2) The ingestion inventory doesn't include any BigCouch nodes, so that playbook will fail. You'll probably just need to create the index manually using the Rake task invoked by `create_index_and_river.sh`. We'll look at fixing this soon.

**Comment by mjsuhonos** [comment]
Thanks @anarchivist; I wasn't sure what the heck I was doing, so diving into the rake tasks directly is actually a perfect entry point into the platform for me.  I'll consider this issue resolved but defer to you on closing it.

**Comment by anarchivist** [comment]
Got it, thanks. Also: if you start digging into the API code, the `ingestion` inventory shouldn't need BigCouch (at least out of the box) since by default the API key authentication/authorization is disabled.

**Comment by anarchivist** [comment]
ref https://issues.dp.la/issues/8143
