### ISSUE TITLE
Fix delayed_job cleanup ["pkill", "-9", "-f", "delayed_job"]

### ISSUE THREAD

**Issue by telezoic** [dpla/automation#148]
I've evened up my fork with the latest release, and re-installing on my local machine I get and error at he end of the invocations section in README-ingestion2.md:
 
```$ ansible-playbook -i ingestion -u <your username in group_vars/all> \
  dev_ingestion_all.yml --extra-vars "initial_run=true"```

The error: 
```TASK [api : Stop obsolete delayed_job if it is running] ************************```
```fatal: [dev1]: FAILED! => {"changed": true, "cmd": ["pkill", "-9", "-f", "delayed_job"], "delta": "0:00:00.003681", "end": "2016-01-29 13:10:56.166660" . . .  ```

I try a ```vagrant reload``` to no effect. I'm hoping you could point me in the right direction to solving this.

**Comment by markbreedlove** [comment]
Thanks for reporting this. I'll have a look soon.
Just to make sure I understand clearly, is this a new installation on a new VM?  (You mentioned re-installing, and you're running with `initial_run=true`.)

**Comment by telezoic** [comment]
Correct. New VM and with ```initial_run=true```. I'm going to come at this one more time in the interim.

**Comment by markbreedlove** [comment]
This is probably the problem.  If a process is not running, `pkill` says "Killed" but returns nonzero. That's getting interpreted (rightly) as failure by ansible.
```
mb@dev1:~$ ps auxw | grep [d]elayed
mb@dev1:~$ sudo pkill -9 -f delayed_job
Killed
mb@dev1:~$ echo $?
137
```

I think it'll be safe to have the task ignore errors.

**Comment by telezoic** [comment]
I set it to ignore for now and all is well. Thanks for this!
